### ISSUE TITLE
Хранение файлов не локально, а во внешнем хранилище

### ISSUE THREAD

**Issue by binakot** [krddevdays/imageboard#1]
Нужно прикрутить что-то типа https://django-storages.readthedocs.io/en/latest/
Сейчас все выгруженные картинки хранятся в папочке рядом с приложением, при деплое этого в инстанс облака место быстро кончится, и мы встрянем на деньги xD

**Comment by TyVik** [comment]
Залил в мастер :)
Надо определить вот эти переменные окружения - https://github.com/krddevdays/imageboard/blob/master/src/hexchan/settings.py#L130. Там пока захардкожены пока мои настройки, по мере надобности их можно тоже в переменные окружения повытаскивать.

**Comment by binakot** [comment]
@TyVik А зачем `AWS_REGION` в https://github.com/krddevdays/imageboard/blob/master/src/hexchan/settings.py#L132? Просто я не нашел ее в [доке](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html), и в коде нигде не используется.

**Comment by binakot** [comment]
Вот хороший гайд, кстати. Мб @langovoi пригодится, когда он будет выкатывать в прод, хотя у нас Я.Облако, там все может быть немного по-другому https://simpleisbetterthancomplex.com/tutorial/2017/08/01/how-to-setup-amazon-s3-in-a-django-project.html
