### ISSUE TITLE
Логин и пароль суперпользователя через переменные окружения

### ISSUE THREAD

**Issue by binakot** [krddevdays/imageboard#2]
Сейчас после запуска контейнера с приложением приходится вручную изнутри запускать команду `python src/manage.py createsuperuser`, чтобы создать первого суперюзера. Удобно было бы это указывать через переменные окружения и задавать в yaml-файлах.

**Comment by langovoi** [comment]
Дичь какая-то. Просто первый раз руками нужно прогнать, это вполне нормально.

**Comment by sergeibershadsky** [comment]
Это не джанго вей. Один раз этот юзер создается и живет в бд и ничего здесь страшного нет при бутстрапе приложения один раз запустить createsuperuser imho

**Comment by binakot** [comment]
> Дичь какая-то. Просто первый раз руками нужно прогнать, это вполне нормально.

Ты будешь залазить в docker swarm сервис руками и через консоль создавать пользователя? Если да, то ок. Пусть будет так 🗡
